### ISSUE TITLE
About MilkVrBatch-DLNA

### ISSUE THREAD

**Issue by elefanitno** [vrdevman/MilkVr-UMS-BatchMVRL#1]
Hello,
First of all, thank you to share this project. It is nice.
I have a problem when I'm trying to use it because when I use MilkVrBatch-DLNA I can see a mvrl folder, but it is empty. I don't understand why. What am I doing wrong, please? I'm on mac, when I'm on a PC it works.
This is the terminal

sh-3.2# java -jar MilkVrBatch-DLNA.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: MilkVrBatch/MilkVrBatch : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

Thanks for your time.

**Comment by vrdevman** [comment]
Hey

I would suggest trying the Android apk app. It is more up to date (at least as of 4 months ago). You can generate the files directly from you phone without the need of a pc or mac. you just need a UMS server running. I have a UMS server running from an android media box running linux and it works great (low power consumption)

If you got it working with PC then it should work with android no problem

Here is the reddit post for the android app
https://www.reddit.com/r/GearVR/comments/4e35nq/easy_dlna_streaming_multiple_videos_thumbnails/

here is the project
https://github.com/vrdevman/MilkVrBatch

and here is the download link
https://raw.githubusercontent.com/vrdevman/MilkVrBatch/master/RELEASES/MilkVRBatch.apk
